services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Optional: Add Supabase local development
  # supabase:
  #   image: supabase/postgres:15.1.0.117
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: your-super-secret-and-long-postgres-password
  #   ports:
  #     - "54322:5432"
  #   volumes:
  #     - supabase_db_data:/var/lib/postgresql/data
# volumes:
#   supabase_db_data:
