version: '3.8'

services:
  # Main React application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - supabase-db
    networks:
      - app-network

  # Supabase Database (for local development)
  supabase-db:
    image: postgres:15-alpine
    container_name: supabase-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network

  # Supabase Edge Runtime (for local development)
  supabase-edge-runtime:
    image: supabase/edge-runtime:latest
    container_name: supabase-edge-runtime
    environment:
      - SUPABASE_URL=http://supabase-db:5432
      - SUPABASE_ANON_KEY=your_anon_key_here
      - SUPABASE_SERVICE_ROLE_KEY=your_service_role_key_here
    ports:
      - "8000:8000"
    volumes:
      - ./supabase/functions:/home/deno/functions
    restart: unless-stopped
    depends_on:
      - supabase-db
    networks:
      - app-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge