-- Migration: Update letters table schema to match application requirements
-- Created: 2024-01-03

-- Add missing columns to letters table
ALTER TABLE public.letters 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS recipient_info JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS sender_info JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
ADD COLUMN IF NOT EXISTS due_date DATE,
ADD COLUMN IF NOT EXISTS ai_generated_content TEXT,
ADD COLUMN IF NOT EXISTS template_data JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS final_content TEXT;

-- Rename existing columns to match application expectations
ALTER TABLE public.letters RENAME COLUMN content TO ai_draft;

-- Update the status constraint to match the new workflow
ALTER TABLE public.letters
DROP CONSTRAINT IF EXISTS letters_status_check;

ALTER TABLE public.letters
ADD CONSTRAINT letters_status_check
CHECK (status IN ('draft', 'submitted', 'in_review', 'approved', 'completed', 'cancelled'));

-- Update default status
ALTER TABLE public.letters
ALTER COLUMN status SET DEFAULT 'submitted';

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_letters_user_id ON public.letters(user_id);
CREATE INDEX IF NOT EXISTS idx_letters_status ON public.letters(status);
CREATE INDEX IF NOT EXISTS idx_letters_priority ON public.letters(priority);
CREATE INDEX IF NOT EXISTS idx_letters_created_at ON public.letters(created_at);
CREATE INDEX IF NOT EXISTS idx_letters_letter_type ON public.letters(letter_type);

-- Add comments
COMMENT ON COLUMN public.letters.description IS 'Additional context or description for the letter';
COMMENT ON COLUMN public.letters.recipient_info IS 'Information about the letter recipient (JSON)';
COMMENT ON COLUMN public.letters.sender_info IS 'Information about the letter sender (JSON)';
COMMENT ON COLUMN public.letters.priority IS 'Priority level of the letter request';
COMMENT ON COLUMN public.letters.due_date IS 'Due date for the letter completion';
COMMENT ON COLUMN public.letters.ai_generated_content IS 'Content generated by AI';
COMMENT ON COLUMN public.letters.template_data IS 'User input data for template fields (JSON)';
COMMENT ON COLUMN public.letters.final_content IS 'Final approved content of the letter';
COMMENT ON COLUMN public.letters.ai_draft IS 'AI-generated draft content';
